name: storage
description: A Key/Value Secure Storage Client
publish_to: none

environment: 
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.24.5

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.1.0
